"""Twitter accounts management and configuration"""

# for twbot/management/commands/auto_engage.py
# please update them regularly
import random
PCS = (
        ("1", "1"),
        ("2", "2"),
        ("3", "3"),
        ("4", "4"),
        ("5", "5"),
        ("6", "6"),
        ("7", "7"),
        ("8", "8"),
        ("9", "9"),
        ("10", "10"),
        ("11", "11"),
        ("12", "12"),
        ("13", "13"),
        ("14", "14"),
        ("15", "15"),
        ("16", "16"),
        ("17", "17"),
        ("18", "18"),
        ("19", "19"),
        ("20", "20"),
        ("21", "21"),
        ("22", "22"),
        ("23", "23"),
        ("24", "24"),
        ("25", "25")
    )
FOLLOW_INTERNAL_ACCOUNTS_MIN_NUMBER = 5
FOLLOW_INTERNAL_ACCOUNTS_MAX_NUMBER = 10
FOLLOW_OTHER_ACCOUNTS_MAX_NUMBER = 3
FOLLOW_OTHER_ACCOUNTS = [
    'elonmusk',
    'Tesla',
    'Ripple',
    'Apple',
    'AppleTV',
    'Google',
    'gmail',
    'GoogleAI',
    'GoogleNews',
    'GoogleDrive',
    'bopinion',
    'washingtonpost',
    'BrusselsTimes',
    'GuyReuters',
    'ThePSF',
    'Reuters',
    'BuffaloBills',
    'CNET',

    'CalMatters',
    'xanalia_nft',

    'crypto',
    'cryptocom',
    'CryptoRank_io',
    'yumcrypto',
    'crypto_banter',
    'TheCryptoDog',
    'CiervoKing',
    'CryptoYoda1338',
    'Bitboy_Crypto',
    'bitcoin160',
    'RealMoneyApe',
    'CryptoKaleo',
    'StanfordCrypto',
    'cryptocomcs',
    'TrustWallet',
    'TheCryptoLark',
    'CryptoRelief_',
    'JRNYcrypto',
    'taylorcaniff',
    'CryptoFinally',
    'crypto_futur',
    'CryptoArch1tect',
    'CryptoCapo_',
    'givecrypto',
    'CryptoTigerBtc',
    'crypto_bitlord7',
    'ladycryptogem',
    'CryptoEthereal',
    'MrMadCrypto',
    'CoinersTakingLs',
    'CryptoWhale',
    'CRC_Crypto',
    'BETSoulTV',
    'MisturBets',
    'BET',
    'PLLBet',
    'BETAwards',
    'HipHopAwards',
    'BETMusic',
    'ColossusBets',
    'BetsByBob',
    'SkyBetChamp',
    'BETNews',
    'LogiqBets',
    'SkyBetLeagueTwo',
    'SportyBet',
    'BET_UK',
    'bet365',
    'SkyBetLeagueOne',
    'americansoulbet',
    'Bet_Labs',
    'BigTipsterr',
    'MyBetsCash',
    'GirlWhoBets',
    'BetCIub',
    'Bambino_Bets',
    'SistasOnBET',
    'OutKickBets',
    'TheGameBET',
    'BetsBarnes',
    'PointsBetUSA',
    'BetCIubVip',
    'betthehoops',
    'PointsBet_AU',
    'betthepigskin',
    'MuseumModernArt',
    'GoogleAI',
    'KensingtonRoyal',
    'LACMA',
    'Isaac_A_Arthur',
    'FreerSackler',
    'RattyBurvil',
    'ArtBasel',
    'ArthurLupia',
    'ArthurMasuaku',
    'newmuseum',
    'artinfodotcom',
    'artnews',
    'metmuseum',
    'art2gee',
    'JamesArthur23',
    'AlexArthur1',
    'SchomburgCenter',
    'MACcosmetics',
    'MOCAlosangeles',
    'philamuseum',
    'artsmia',
    'whitneymuseum',
    'artinstitutechi',
    'ngadc',
    'walters_museum',
    'dabody52',
    'arthurbrooks',
    'QueensMuseum',
    'agotoronto',
    'BillGalston',
    'ArtReview_',
    'cryptoartist78',
    'Flik_art',
    'MasakicryptoArt',
    'Goooooonel',
    'FCryptoartist',
    'lukedignom',
    'Cryptoartist5',
    'cryptoartist8',
    'Crypt0Art',
    'cryptoartist0',
    'fredsgallery',
    'iamcryptoartist',
    'Wurmhat99',
    'cryptopom1',
    'LuchoPoletti',
    'JAY_MEDICI',
    'orla_morna',
    'AlexFiginiArt',
    'TroyFitzpatric',
    'icetoy008',
    'P3RS0NAZ',
    'FiveTimesNo',
    'Waxbones',
    'fiedler_jpg',
    'Natural_Warp',
    'polly_kole',
    'nftomatic',
    'ericprhodes',
    'osinachiart',
    'pepe_designer',
    'DaniellaDoodles',
    'casinoonline7',
    'casinoonline123',
    'casinoonline0',
    'casinoonline_UK',
    'casinonlineSofi',
    'casinoonline66',
    'CasinoOnline',
    'CasinoonlineN',
    'CasinoOnlineDEU',
    'casinoonline553',
    'CasinoOnline_',
    'CasinoonlineIT',
    'myhotcasino',
    'casinoonline771',
    'casinoonline_us',
    '999casinoonline',
    'notiziecasino',
    'casinoonline112',
    'casinoonline_co',
    'Casinoonline14',
    'CASINOONLINE05',
    'casinoonline24',
    'Casinos_Offers',
    'Casinoonline_es',
]

NEW_POST_USER_NAMES = [
    #  "rhian_highsmith",
    #  'Richard52562618',
    #  'xanalia_nft',
]
NEW_POST_USER_NAMES_NUMBER = 1  # the number to select randomly, for NEW_POST_USER_NAMES
# don't comment on these external accounts
NEW_POST_EXTERNAL_USER_NAMES = [
    'xanalia_nft',
    'xana_metaverse',
    'xanametaverse',
    'rio_noborderz',
    'xanalia_promo_',
    'xanalia_promo',
    'ultramannft',
    'nftnewznet'

    #  'elonmusk',
    #  'Tesla',
    #  'Ripple',
    #  'Apple',
    #  'AppleTV',
    #  'Google',
    #  'gmail',
    #  'GoogleAI',
    #  'GoogleNews',
    #  'GoogleDrive',
    #  'bopinion',
    #  'washingtonpost',
    #  'BrusselsTimes',
    #  'GuyReuters',
    #  'ThePSF',
    #  'Reuters',
    #  'BuffaloBills',
    #  'CNET',
    #
    #  'CalMatters',
    #  'xanalia_nft',
    #
    #  'crypto',
    #  'cryptocom',
    #  'CryptoRank_io',
    #  'yumcrypto',
    #  'crypto_banter',
]
NEW_POST_EXTERNAL_USER_NAMES_NUMBER = 2  # the number to select randomly

# content generating
TWEET_KEYWORDS = [
    "DeFi",
    "BTC",
    "BNB ",
    "Binance",
    "BSC",
    "NFTs ",
    "nftart ",
    "NFTCommunity ",
    "nftcollector ",
    "NFT",
    "NFTdrop",
    "NFTcollection ",
    "cryptoart",
    "digitalart",
    "DigitalArtist ",
    "NFTartist",
    "artwork",
    "NFTartwork",
    "BinanceSmartChain",
    "staking",
    "cryptocurrency ",
    "crypto ",
    "cryptocurrencies",
    "NFTcollectible",
    "cryptoartist ",
    "marketplace",
    "artlovers",
    "galleryart",
    "dailyart ",
    "3Dart",
    "digitalpainting",
    "art",
    "artist",
    "digitalartwork",
    "NFTmarketplace",
    "AR",
    "VR",
    "polygon",
    "polygonChain",
    "ALIA",
    "cryptotoken",
    "cryptostaking",
    "BSCtoken",
    "decentralized",
    "CryptoExchange",
    "galleryart",
    "onlinegallery",
    "nftmarket",
    "cryptocurrencies",
    "BNB",
    "YieldFarming",
    "DeFi",
    "BSC",
    "cryptogaming",
    "cryptogame",
    "cryptogames",
    "playtoearn",
    "DefiGaming",
    "Gaming",
    "betting",
    "casino",
    "game",
    "games",
    "gamers",
    "virtualgame",
    "crypto",
    "bet",
    "bets",
    "poker",
    "slotgame",
    "CasinoCoin",
    "casinoonline",
    "cryptopunks",
    "staking",
    "cryptocurrency",
    "passiveincome",
    "BSCGems",
    "Binance",
    "BinanceSmartChain",
    "cryptofarming",
    "cryptostaking",
    "cryptomining",
    "BSCtoken",
    "cryptomarket",
    "YieldFarm",
    "CryptoYield",
    "cryptotoken",
    "token",
    "cryptoreward",
    "earncrypto",
    "entertainment",
    "virtualland",
    "onlinegame",
    "onlinecasinogame",
    "bonus",
    "cryptotrading",
    "exchange",
    "decentralized",
    "CryptoExchange",
]

# nord vpn account
NORDVPN_ACCOUNTS = [
    {
        'username': 'pay@noborders.net',
        'password': 'xF#Ng=`Y*dS74\\S\\',
    },
    {
        'username': 'Py@noborderz.com',
        'password': 'Noborderz@1414',
    },
]

# cyberghostvpn account
CYBERGHOSTVPN_USERNAME = 'salman@noborderz.com'
CYBERGHOSTVPN_PASSWORD = 'Surviral#123'

# GETSMSCODE API Key
GETSMSCODE_API_KEY = "6c42bc9b6dcfa54151f620293d4dcbd8"
GETSMSCODE_PID = '928'

RANDOM_LIKE_MAX_NUMBER = 5
RANDOM_FOLLOW_MAX_NUMBER = 5

CREATE_TWEET_MIN_NUMBER = 2

# Range of accounts for Engagement
ENGAGEMENT_ACCOUNTS_RANGE = random.randint(70, 85)

# engagement number in a week
LIKE_MIN_NUMBER_IN_A_WEEK = 150
RETWEET_MIN_NUMBER_IN_A_WEEK = 100
COMMENT_MIN_NUMBER_IN_A_WEEK = 30
