COUNTRIES = [
    "Argentina",
    "Brazil",
    "Canada",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Mexico",
    "Paraguay",
    "United States",
    "Australia",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Malaysia",
    "New Zealand",
    "Philippines",
    "Singapore",
    "South Korea",
    "Taiwan",
    "Thailand",
    "Vietnam",
    "Israel",
    "Libya",
    "Nigeria",
    "South Africa",
    "United Arab Emirates",
    "Albania",
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Luxembourg",
    "Moldova",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom",
]

VPN_COUNTRIES = [
    "Bend",
    "Atlanta",
    "Boston",
    "Buffalo",
    "Charlotte",
    "Chicago",
    "Dallas",
    "Denver",
    "Detroit",
    "Houston",
    "Kansas City",
    "Las Vegas",
    "Latham",
    "Los Angeles",
    "Miami",
    "New York",
    "Glasgow",
    "Manchester",
    "London",
]

SHADOWSOCKS = [
    "ae-dub.prod.surfshark.com",
    "al-tia.prod.surfshark.com",
    "ar-bua.prod.surfshark.com",
    "at-vie.prod.surfshark.com",
    "au-adl.prod.surfshark.com",
    "au-bne.prod.surfshark.com",
    "au-mel.prod.surfshark.com",
    "au-per.prod.surfshark.com",
    "au-syd.prod.surfshark.com",
    "az-bak.prod.surfshark.com",
    "ba-sjj.prod.surfshark.com",
    "be-bru.prod.surfshark.com",
    "bg-sof.prod.surfshark.com",
    "br-sao.prod.surfshark.com",
    "ca-mon.prod.surfshark.com",
    "ca-tor-mp001.prod.surfshark.com",
    "ca-tor.prod.surfshark.com",
    "ca-van.prod.surfshark.com",
    "ch-zur.prod.surfshark.com",
    "cl-san.prod.surfshark.com",
    "co-bog.prod.surfshark.com",
    "cr-sjn.prod.surfshark.com",
    "cy-nic.prod.surfshark.com",
    "cz-prg.prod.surfshark.com",
    "de-ber.prod.surfshark.com",
    "de-fra-mp001.prod.surfshark.com",
    "de-fra.prod.surfshark.com",
    "de-fra-st001.prod.surfshark.com",
    "de-fra-st002.prod.surfshark.com",
    "de-fra-st003.prod.surfshark.com",
    "de-fra-st004.prod.surfshark.com",
    "de-fra-st005.prod.surfshark.com",
    "de-muc.prod.surfshark.com",
    "de-nue.prod.surfshark.com",
    "dk-cph.prod.surfshark.com",
    "ee-tll.prod.surfshark.com",
    "es-bcn.prod.surfshark.com",
    "es-mad.prod.surfshark.com",
    "es-vlc.prod.surfshark.com",
    "fi-hel.prod.surfshark.com",
    "fr-bod.prod.surfshark.com",
    "fr-mrs.prod.surfshark.com",
    "fr-par.prod.surfshark.com",
    "gr-ath.prod.surfshark.com",
    "hk-hkg.prod.surfshark.com",
    "hr-zag.prod.surfshark.com",
    "hu-bud.prod.surfshark.com",
    "id-jak.prod.surfshark.com",
    "ie-dub.prod.surfshark.com",
    "il-tlv.prod.surfshark.com",
    "in-chn.prod.surfshark.com",
    "in-idr.prod.surfshark.com",
    "in-mum.prod.surfshark.com",
    "is-rkv.prod.surfshark.com",
    "it-mil.prod.surfshark.com",
    "it-rom.prod.surfshark.com",
    "jp-tok.prod.surfshark.com",
    "jp-tok-st001.prod.surfshark.com",
    "jp-tok-st002.prod.surfshark.com",
    "jp-tok-st003.prod.surfshark.com",
    "jp-tok-st004.prod.surfshark.com",
    "jp-tok-st005.prod.surfshark.com",
    "jp-tok-st008.prod.surfshark.com",
    "jp-tok-st009.prod.surfshark.com",
    "jp-tok-st010.prod.surfshark.com",
    "jp-tok-st011.prod.surfshark.com",
    "jp-tok-st012.prod.surfshark.com",
    "jp-tok-st013.prod.surfshark.com",
    "kr-seo.prod.surfshark.com",
    "kz-ura.prod.surfshark.com",
    "lu-ste.prod.surfshark.com",
    "lv-rig.prod.surfshark.com",
    "md-chi.prod.surfshark.com",
    "mk-skp.prod.surfshark.com",
    "mx-mex.prod.surfshark.com",
    "my-kul.prod.surfshark.com",
    "ng-lag.prod.surfshark.com",
    "nl-ams-mp001.prod.surfshark.com",
    "nl-ams.prod.surfshark.com",
    "no-osl.prod.surfshark.com",
    "nz-akl.prod.surfshark.com",
    "ph-mnl.prod.surfshark.com",
    "pl-gdn.prod.surfshark.com",
    "pl-waw.prod.surfshark.com",
    "pt-lis.prod.surfshark.com",
    "pt-opo.prod.surfshark.com",
    "py-asu.prod.surfshark.com",
    "ro-buc.prod.surfshark.com",
    "rs-beg.prod.surfshark.com",
    "ru-mos.prod.surfshark.com",
    "se-sto.prod.surfshark.com",
    "sg-in.prod.surfshark.com",
    "sg-sng-mp001.prod.surfshark.com",
    "sg-sng.prod.surfshark.com",
    "sg-sng-st001.prod.surfshark.com",
    "sg-sng-st002.prod.surfshark.com",
    "sg-sng-st003.prod.surfshark.com",
    "sg-sng-st004.prod.surfshark.com",
    "si-lju.prod.surfshark.com",
    "sk-bts.prod.surfshark.com",
    "th-bkk.prod.surfshark.com",
    "tr-ist.prod.surfshark.com",
    "tw-tai.prod.surfshark.com",
    "ua-iev.prod.surfshark.com",
    "uk-gla.prod.surfshark.com",
    "uk-lon-mp001.prod.surfshark.com",
    "uk-lon.prod.surfshark.com",
    "uk-lon-st001.prod.surfshark.com",
    "uk-lon-st002.prod.surfshark.com",
    "uk-lon-st003.prod.surfshark.com",
    "uk-lon-st004.prod.surfshark.com",
    "uk-lon-st005.prod.surfshark.com",
    "uk-man.prod.surfshark.com",
    "us-atl.prod.surfshark.com",
    "us-bdn.prod.surfshark.com",
    "us-bos.prod.surfshark.com",
    "us-buf.prod.surfshark.com",
    "us-chi.prod.surfshark.com",
    "us-clt.prod.surfshark.com",
    "us-dal.prod.surfshark.com",
    "us-den.prod.surfshark.com",
    "us-dtw.prod.surfshark.com",
    "us-hou.prod.surfshark.com",
    "us-kan.prod.surfshark.com",
    "us-las.prod.surfshark.com",
    "us-lax.prod.surfshark.com",
    "us-ltm.prod.surfshark.com",
    "us-mia.prod.surfshark.com",
    "us-mnz.prod.surfshark.com",
    "us-nyc-mp001.prod.surfshark.com",
    "us-nyc.prod.surfshark.com",
    "us-nyc-st001.prod.surfshark.com",
    "us-nyc-st002.prod.surfshark.com",
    "us-nyc-st003.prod.surfshark.com",
    "us-nyc-st004.prod.surfshark.com",
    "us-nyc-st005.prod.surfshark.com",
    "us-orl.prod.surfshark.com",
    "us-phx.prod.surfshark.com",
    "us-sea.prod.surfshark.com",
    "us-sfo-mp001.prod.surfshark.com",
    "us-sfo.prod.surfshark.com",
    "us-slc.prod.surfshark.com",
    "us-stl.prod.surfshark.com",
    "us-tpa.prod.surfshark.com",
    "vn-hcm.prod.surfshark.com",
    "za-jnb.prod.surfshark.com",
]

COMMENTS = [
    "What are you guys still waiting for? This is going to be outstanding",
    "This is a very excellent project",
    "Join this good and reliable project, don't miss, join now to participate in the project",
    "Super projectHeading to the mooon Thanks for the opportunity",
    "Please guys let's make this free coin together",
    "This is cool and you wouldn't want to miss out...",
    "Wonderful project. This gonna rule the world soon",
    "Great project with great prospect",
    "What an amazing project keep moving to the moon",
    "No one should miss this opportunity",
    "I'm seeing the fun in the games already.",
    "I'm very excited for this strong project",
    "I hope this project is a success, sir and then it becomes one of the best",
    "It's a very strong project. I think it will give a big profit in future. So, please join",
    "Very nice project and a very strong  team behind",
    "I am very happy to see such a beautiful project. I hope its future is very bright. This project is one of the best projects in favor of grace.",
    "Congratulations, I hope the project will progress and the project will be more successful",
    "I'm looking forward to this project.",
    "Bro... legitimately one of the coolest things I've ever seen",
    "Oh, I really like cute stuff I wish I can have it on my collection.",
    "Great product, innovative technology. $xyz, the future is yours!",
    "Can't wait to see Tim's #NFT collection!",
    "Hello, This is the TRUST WALLET Help Desk, Send a Direct message explaining your issue and kindly follow back so that I can assist you",
    "Real project. Together we strong!!!",
    "This is real-time data. Organics makes perfect",
    "A master's work. Well done",
    "I love your NFTs! You have a wonderfully unique idea.",
    "This project is good and helpful for the future.",
    "Amazing platform for earn money via doing almost nothing",
    "One of the best Roadmaps I've seen for a crypto. you definitely has high potential",
    "Don't Sleep on this !! Real Defi !!",
    "Well designed projects, a good and reliable team, Probably the best investment",
    "This is a wonderful project and, of course, it will have a bright future. Good luck!",
    "Project With Great Idea...... I advise everyone not to slow down and to join the project. I'm sure the project will be successful! Good Luck my friends....!!",
    "Can't wait for more updates",
    "I am really surprised. Suddenly see your application. This is really wonderful project. Have a nice day. God Bless You.",
    "This was a good partnership, I hope they keep on it, Also BSC is kinda booming now",
    "Hello sir, I suddenly see your project. & I am impressed",
    "With more progress and success, God willing, greater expansion in the field and financial transactions, and a greater investment volume.",
    "Wow awesome video I really like this video I appreciate thanks for sharing this awesome video with us good job keep it up",
    "Wow, cool! Keep working guys! All support for your team!",
    "I bet they're going to replace the sun WITH A MOON",
    "Don't miss it guys and good luck with this awesome NFTs",
    "Origin City! That's a great price! Welcome to the world!",
    "At this time a great project for crypto assets. I wish the owners and staff a healthy and successful life for your company. Best wishes for this project",
    "Hope we see not late to the party",
    "I Think, this is a very strong project Thanks for sharing this wonderful opportunity Best wishes for all team member",
    "Thank you so much for giving us this great opportunity. We are all so excited about this great event",
    "This is gonna be a great and awesome project, with the liquidity and others, Great Project! Hope this project is a success I'm so enthusiast",
    "This is a great project, built with careful planning, and on the run with a great concept by a great team. project with a higher return on investment."
]

XANALIA_COMMENTS = [
    "Stunning! So proud of you and this will slaaaay!",
    "Beautiful! Can’t wait to see the more pieces you’ll be dropping.🔥",
    "SOOOO EXCITING!!!😍🔥",
    "Wow, well done! Super inspiring! Best wishes for your drop, no doubt you are about to blow it up!",
    "I love it!!!! Super well done.",
    "This will pay off  you did great lady!❤💕",
    "Stunning piece of art!",
    "Awesome! This is going to be amazing.",
    "This is beyond amazing, Looking forward to the next drop!",
    "Uhhh that’s so great! Will think about it🥳",
    "Let's purchase it! It is really amazing. ",
    "Great work. I loved the colors, textures and shapes. Hope you achieve a lot of success.",
    "💯💯",
    "Really thinking to own this unique piece of history!🥳",
    "Can someone guide me here how to own this amazing piece of art?",
    "Nice Project😍🔥",
    "I want to mint this NFT!💯",
    "This is really an amazing project. Looking forward to mint NFTs!❤",
    "You guys rock! 🚀",
    "Love it! Such projects have a positive impact on the development of the cryptocurrency industry",
    "💟This blew my mind💟",
    "Wow, well done! Super inspiring! Best wishes for  drop, no doubt your project is so inspiring and amazing!",
    "Absolutely the top post of today",
    "Wow so beautiful and gorgeous , You Are my Ideal.",
    "Top nft visit 👉 https://xanalia.com/",
    "Good Luck with the Auction!",
    "Can anyone pleease help me accept a bid that says ‘not found’ when clicking accept bid? And how I may get verified via Instagram instead of Twitter?",
    "What’s up with the XANALIA site?? Whenever I try to accept a bid it says “not found”",
    "Can't wait for the day I got my piece up here!🔥",
    "How do I actually have dialouge with someone from @xanalia",
    "Guys, i have problems with my account in xanalia. Unable to verificate. I send several emails, no response. Could you help? Thanks.",
    "So beautiful😍.i will share this.",
    "Wow that is so awesome! 🔥👏",
    "This is a very special moment in time. Be part of it. Buy an NFT there. Let’s change the path of the arts!",
    "Could you please tell me how to reach customer support?",
    "Hahahaha now that’s an amazing designs 🧡🧡🧡",
    "How to sell in nfts? Does it costs?",
    "Love it!! ❤️❤️",
    "@xanalia Can’t wait to release my collection next month 👏",
    "Added to my NFT Collection love this",
    "Hello @xanalia, please let me know how to make a verified profile? ",
    "Wow this is incredible!",
    "Magic🔥",
    "Great creative with fine detailing",
    "Check out these art please! If you want to buy or sell, this will help to invest in the gas fee for the next pieces and it will also help you in buying art from other artists in the community! https://xanalia.com/",
    "I am lovin'it❤️❤️❤️❤️",
    "Such a Fascinating piece of art 😍🔥",
    "Is this art on atomichub?? I can seem to find any collections of it on there.. what’s the best way to start xanalia?",
    "This one might be my fav!😍🔥"
]

XANALIA_TAGS = [
    "#DeFi",
    "#BTC",
    "#BNB ",
    "#Binance",
    "#BSC",
    "#NFTs ",
    "#nftart ",
    "#NFTCommunity ",
    "#nftcollector ",
    "#NFT",
    "#NFTdrop",
    "#NFTcollection ",
    "#cryptoart",
    "#digitalart",
    "#DigitalArtist ",
    "#NFTartist",
    "#artwork",
    "#NFTartwork",
    "#BinanceSmartChain",
    "#staking",
    "#cryptocurrency ",
    "#crypto ",
    "#cryptocurrencies",
    "#NFTcollectible",
    "#cryptoartist ",
    "#marketplace",
    "#artlovers",
    "#galleryart",
    "#dailyart ",
    "#3Dart",
    "#digitalpainting",
    "#art",
    "#artist",
    "#digitalartwork",
    "#NFTmarketplace",
    "#AR",
    "#VR",
    "#polygon",
    "#polygonChain",
    "#ALIA",
    "#cryptotoken",
    "#cryptostaking",
    "#BSCtoken",
    "#decentralized",
    "#CryptoExchange",
    "#galleryart",
    "#onlinegallery",
    "#nftmarket",
]

CAZICAZI_TAGS = [
    "#cryptocurrencies",
    "#BNB",
    "#YieldFarming",
    "#DeFi",
    "#BSC",
    "#cryptogaming",
    "#cryptogame",
    "#cryptogames",
    "#playtoearn",
    "#DefiGaming",
    "#Gaming",
    "#betting",
    "#casino",
    "#game",
    "#games",
    "#gamers",
    "#virtualgame",
    "#crypto",
    "#bet",
    "#bets",
    "#poker",
    "#slotgame",
    "#CasinoCoin",
    "#casinoonline",
    "#cryptopunks",
    "#staking",
    "#cryptocurrency",
    "#passiveincome",
    "#BSCGems",
    "#Binance",
    "#BinanceSmartChain",
    "#cryptofarming",
    "#cryptostaking",
    "#cryptomining",
    "#BSCtoken",
    "#cryptomarket",
    "#YieldFarm",
    "#CryptoYield",
    "#cryptotoken",
    "#token",
    "#cryptoreward",
    "#earncrypto",
    "#entertainment",
    "#virtualland",
    "#onlinegame",
    "#onlinecasinogame",
    "#bonus",
    "#cryptotrading",
    "#exchange",
    "#decentralized",
    "#CryptoExchange",
]

ACC_BATCH = (
    ("BATCH_1", "BATCH_1"),
    ("BATCH_2", "BATCH_2"),
    ("BATCH_3", "BATCH_3"),
    ("BATCH_4", "BATCH_4"),
    ("BATCH_5", "BATCH_5"),
    ("BATCH_6", "BATCH_6"),
    ("BATCH_7", "BATCH_7"),
    ("BATCH_8", "BATCH_8"),
    ("BATCH_9", "BATCH_9"),
    ("BATCH_10", "BATCH_10"),
    ("BATCH_11", "BATCH_11"),
    ("BATCH_12", "BATCH_12"),
    ("BATCH_13", "BATCH_13"),
    ("BATCH_14", "BATCH_14"),
    ("BATCH_15", "BATCH_15"),
    ("BATCH_16", "BATCH_16"),
    ("BATCH_17", "BATCH_17"),
    ("BATCH_18", "BATCH_18"),
    ("BATCH_19", "BATCH_19"),
    ("BATCH_20", "BATCH_20"),
    ("BATCH_21", "BATCH_21"),
    ("BATCH_22", "BATCH_22"),
    ("BATCH_23", "BATCH_23"),
    ("BATCH_24", "BATCH_24"),
    ("BATCH_25", "BATCH_25"),
    ("BATCH_26", "BATCH_26"),
    ("BATCH_27", "BATCH_27"),
    ("BATCH_28", "BATCH_28"),
    ("BATCH_29", "BATCH_29"),
    ("BATCH_30", "BATCH_30"),
    ("BATCH_31", "BATCH_31"),
    ("BATCH_32", "BATCH_32"),
    ("BATCH_33", "BATCH_33"),
    ("BATCH_34", "BATCH_34"),
    ("BATCH_35", "BATCH_35"),
    ("BATCH_36", "BATCH_36"),
    ("BATCH_37", "BATCH_37"),
    ("BATCH_38", "BATCH_38"),
    ("BATCH_39", "BATCH_39"),
    ("BATCH_40", "BATCH_40"),
    ("BATCH_41", "BATCH_41"),
    ("BATCH_42", "BATCH_42"),
    ("BATCH_43", "BATCH_43"),
    ("BATCH_44", "BATCH_44"),
    ("BATCH_45", "BATCH_45"),
    ("BATCH_46", "BATCH_46"),
    ("BATCH_47", "BATCH_47"),
    ("BATCH_48", "BATCH_48"),
    ("BATCH_49", "BATCH_49"),
    ("BATCH_50", "BATCH_50"),
)
COUNTRY_CODES = {'af': 'afghanistan', 'al': 'albania', 'dz': 'algeria', 'as': 'american samoa', 'ad': 'andorra',
                 'ao': 'angola', 'ai': 'anguilla', 'aq': 'antarctica', 'ag': 'antigua and barbuda', 'ar': 'argentina',
                 'am': 'armenia', 'aw': 'aruba', 'au': 'australia', 'at': 'austria', 'az': 'azerbaijan',
                 'bs': 'bahamas (the)', 'bh': 'bahrain', 'bd': 'bangladesh', 'bb': 'barbados', 'by': 'belarus',
                 'be': 'belgium', 'bz': 'belize', 'bj': 'benin', 'bm': 'bermuda', 'bt': 'bhutan',
                 'bo': 'bolivia (plurinational state of)', 'bq': 'bonaire, sint eustatius and saba',
                 'ba': 'bosnia and herzegovina', 'bw': 'botswana', 'bv': 'bouvet island', 'br': 'brazil',
                 'io': 'british indian ocean territory (the)', 'bn': 'brunei darussalam', 'bg': 'bulgaria',
                 'bf': 'burkina faso', 'bi': 'burundi', 'cv': 'cabo verde', 'kh': 'cambodia', 'cm': 'cameroon',
                 'ca': 'canada', 'ky': 'cayman islands (the)', 'cf': 'central african republic (the)', 'td': 'chad',
                 'cl': 'chile', 'cn': 'china', 'cx': 'christmas island', 'cc': 'cocos (keeling) islands (the)',
                 'co': 'colombia', 'km': 'comoros (the)', 'cd': 'congo (the democratic republic of the)',
                 'cg': 'congo (the)', 'ck': 'cook islands (the)', 'cr': 'costa rica', 'hr': 'croatia', 'cu': 'cuba',
                 'cw': 'curaçao', 'cy': 'cyprus', 'cz': 'czechia', 'ci': "côte d'ivoire", 'dk': 'denmark',
                 'dj': 'djibouti', 'dm': 'dominica', 'do': 'dominican republic (the)', 'ec': 'ecuador', 'eg': 'egypt',
                 'sv': 'el salvador', 'gq': 'equatorial guinea', 'er': 'eritrea', 'ee': 'estonia', 'sz': 'eswatini',
                 'et': 'ethiopia', 'fk': 'falkland islands (the) [malvinas]', 'fo': 'faroe islands (the)', 'fj': 'fiji',
                 'fi': 'finland', 'fr': 'france', 'gf': 'french guiana', 'pf': 'french polynesia',
                 'tf': 'french southern territories (the)', 'ga': 'gabon', 'gm': 'gambia (the)', 'ge': 'georgia',
                 'de': 'germany', 'gh': 'ghana', 'gi': 'gibraltar', 'gr': 'greece', 'gl': 'greenland', 'gd': 'grenada',
                 'gp': 'guadeloupe', 'gu': 'guam', 'gt': 'guatemala', 'gg': 'guernsey', 'gn': 'guinea',
                 'gw': 'guinea-bissau', 'gy': 'guyana', 'ht': 'haiti', 'hm': 'heard island and mcdonald islands',
                 'va': 'holy see (the)', 'hn': 'honduras', 'hk': 'hong kong', 'hu': 'hungary', 'is': 'iceland',
                 'in': 'india', 'id': 'indonesia', 'ir': 'iran (islamic republic of)', 'iq': 'iraq', 'ie': 'ireland',
                 'im': 'isle of man', 'il': 'israel', 'it': 'italy', 'jm': 'jamaica', 'jp': 'japan', 'je': 'jersey',
                 'jo': 'jordan', 'kz': 'kazakhstan', 'ke': 'kenya', 'ki': 'kiribati',
                 'kp': "korea (the democratic people's republic of)", 'kr': 'korea (the republic of)', 'kw': 'kuwait',
                 'kg': 'kyrgyzstan', 'la': "lao people's democratic republic (the)", 'lv': 'latvia', 'lb': 'lebanon',
                 'ls': 'lesotho', 'lr': 'liberia', 'ly': 'libya', 'li': 'liechtenstein', 'lt': 'lithuania',
                 'lu': 'luxembourg', 'mo': 'macao', 'mg': 'madagascar', 'mw': 'malawi', 'my': 'malaysia',
                 'mv': 'maldives', 'ml': 'mali', 'mt': 'malta', 'mh': 'marshall islands (the)', 'mq': 'martinique',
                 'mr': 'mauritania', 'mu': 'mauritius', 'yt': 'mayotte', 'mx': 'mexico',
                 'fm': 'micronesia (federated states of)', 'md': 'moldova (the republic of)', 'mc': 'monaco',
                 'mn': 'mongolia', 'me': 'montenegro', 'ms': 'montserrat', 'ma': 'morocco', 'mz': 'mozambique',
                 'mm': 'myanmar', 'na': 'namibia', 'nr': 'nauru', 'np': 'nepal', 'nl': 'netherlands (the)',
                 'nc': 'new caledonia', 'nz': 'new zealand', 'ni': 'nicaragua', 'ne': 'niger (the)', 'ng': 'nigeria',
                 'nu': 'niue', 'nf': 'norfolk island', 'mp': 'northern mariana islands (the)', 'no': 'norway',
                 'om': 'oman', 'pk': 'pakistan', 'pw': 'palau', 'ps': 'palestine, state of', 'pa': 'panama',
                 'pg': 'papua new guinea', 'py': 'paraguay', 'pe': 'peru', 'ph': 'philippines (the)', 'pn': 'pitcairn',
                 'pl': 'poland', 'pt': 'portugal', 'pr': 'puerto rico', 'qa': 'qatar',
                 'mk': 'republic of north macedonia', 'ro': 'romania', 'ru': 'russian federation (the)', 'rw': 'rwanda',
                 're': 'réunion', 'bl': 'saint barthélemy', 'sh': 'saint helena, ascension and tristan da cunha',
                 'kn': 'saint kitts and nevis', 'lc': 'saint lucia', 'mf': 'saint martin (french part)',
                 'pm': 'saint pierre and miquelon', 'vc': 'saint vincent and the grenadines', 'ws': 'samoa',
                 'sm': 'san marino', 'st': 'sao tome and principe', 'sa': 'saudi arabia', 'sn': 'senegal',
                 'rs': 'serbia', 'sc': 'seychelles', 'sl': 'sierra leone', 'sg': 'singapore',
                 'sx': 'sint maarten (dutch part)', 'sk': 'slovakia', 'si': 'slovenia', 'sb': 'solomon islands',
                 'so': 'somalia', 'za': 'south africa', 'gs': 'south georgia and the south sandwich islands',
                 'ss': 'south sudan', 'es': 'spain', 'lk': 'sri lanka', 'sd': 'sudan (the)', 'sr': 'suriname',
                 'sj': 'svalbard and jan mayen', 'se': 'sweden', 'ch': 'switzerland', 'sy': 'syrian arab republic',
                 'tw': 'taiwan (province of china)', 'tj': 'tajikistan', 'tz': 'tanzania, united republic of',
                 'th': 'thailand', 'tl': 'timor-leste', 'tg': 'togo', 'tk': 'tokelau', 'to': 'tonga',
                 'tt': 'trinidad and tobago', 'tn': 'tunisia', 'tr': 'turkey', 'tm': 'turkmenistan',
                 'tc': 'turks and caicos islands (the)', 'tv': 'tuvalu', 'ug': 'uganda', 'ua': 'ukraine',
                 'ae': 'united arab emirates (the)', 'gb': 'united kingdom of great britain and northern ireland (the)',
                 'um': 'united states minor outlying islands (the)', 'us': 'united states of america (the)',
                 'uy': 'uruguay', 'uz': 'uzbekistan', 'vu': 'vanuatu', 've': 'venezuela (bolivarian republic of)',
                 'vn': 'viet nam', 'vg': 'virgin islands (british)', 'vi': 'virgin islands (u.s.)',
                 'wf': 'wallis and futuna', 'eh': 'western sahara', 'ye': 'yemen', 'zm': 'zambia', 'zw': 'zimbabwe',
                 'ax': 'åland islands'}

# for twbot/engagement/compound_actions.py
# please input more and update them frequently
TOP_ACCS = [
    "rarible",
    "SuperRare",
    "nonfungibles",
    "DappRadar",
    "niftygateway",
    "WazirXNFT",
    'schauermann_',
    'ApeRocketFi',
    'Metahero_io',
    'Merrymodz_io',
    'genopets',
    'solana',
    'GoGalaGames',
    'cryptovoxels',
    'PositionEx',
    'traderjoe_xyz',
    'avalancheavax',
    'mimoprotocol',
    'iotex_io',
    'Solana',
    'VulcanForged',
    'VulcanVerse',
    'Berserk_Game',
    'AxieInfinity',
    'AtomicHub',
    'larvalabs',
    'agicEden_NFT',
]

TRENDING_POSTS_COMMENTS = [
    f'''XANALIA, the best-decentralized multi-chain NFT marketplace on BSC, ETH, and Polygon, is awaiting potential collaborations from NFT artists. Follow our Twitter right away 👉 https://twitter.com/xanalia_nft/, to know more about the NFT trading, reward details, and upcoming announcements!'''
]
