# Generated by Django 3.2.3 on 2022-06-09 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('app_choice', models.CharField(choices=[('IG', 'IG'), ('TT', 'TT'), ('YT', 'YT'), ('TW', 'TW'), ('TL', 'TL')], default='IG', max_length=200)),
                ('user_type', models.CharField(choices=[('marketing_team', 'marketing_team'), ('tester', 'tester'), ('user', 'user')], default='user', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_language', models.CharField(choices=[('en-us', 'English'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh_CN', 'Chinese')], default='en-us', max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engagement_agent_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('agent_user', models.CharField(blank=True, max_length=255, null=True)),
                ('total_likes', models.IntegerField(blank=True, null=True)),
                ('total_shares', models.IntegerField(blank=True, null=True)),
                ('total_comments', models.IntegerField(blank=True, null=True)),
                ('total_follow', models.IntegerField(blank=True, null=True)),
                ('liked', models.IntegerField(default=0)),
                ('commented', models.IntegerField(default=0)),
                ('followed', models.IntegerField(default=0)),
                ('shared', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngageTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target_name', models.CharField(max_length=300)),
                ('tweet_id', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('DONE', 'DONE'), ('RUNNING', 'RUNNING')], default='PENDING', max_length=200)),
                ('system_no', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25')], max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='instagram_report_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25')], max_length=255, null=True)),
                ('total_Account', models.IntegerField()),
                ('total_eligible_for_engagement_account', models.IntegerField()),
                ('total_active_accounts', models.IntegerField()),
                ('total_issued_accounts_in_login', models.IntegerField()),
                ('total_updated_accounts', models.IntegerField()),
                ('total_random_action', models.IntegerField()),
                ('total_accounts_under_warm_up', models.IntegerField()),
                ('total_likes', models.IntegerField()),
                ('total_comments', models.IntegerField()),
                ('total_share', models.IntegerField()),
                ('total_follow', models.IntegerField()),
                ('total_action', models.IntegerField()),
                ('total_accounts_created_in_last_24hours', models.IntegerField()),
                ('total_new_eligible_accounts_in_login_in_last_24hours', models.IntegerField()),
                ('total_issued_accounts_in_login_in_last_24hours', models.IntegerField()),
                ('total_accounts_updated_in_last_24hours', models.IntegerField()),
                ('total_random_action_performed_in_24hours', models.IntegerField()),
                ('total_accounts_added_under_warm_upin_last_24hours', models.IntegerField()),
                ('total_likes_in_last_24hours', models.IntegerField()),
                ('total_comments_in_last_24hours', models.IntegerField()),
                ('total_share_in_last_24hours', models.IntegerField()),
                ('total_follow_in_last_24hours', models.IntegerField()),
                ('total_action_performed_in_last_24hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avdsname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('number', models.BigIntegerField()),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('birth_month', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('updated', models.BooleanField(default=False)),
                ('random_action', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LOGIN_ISSUE', 'LOGIN_ISSUE')], default='ACTIVE', max_length=255)),
                ('following', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('can_search', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('like', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('share', models.IntegerField()),
                ('follow', models.IntegerField()),
                ('action_type', models.CharField(choices=[('RANDOM', 'RANDOM'), ('ENGAGEMENT', 'ENGAGEMENT'), ('NOT_DEFINED', 'NOT_DEFINED')], default='NOT_DEFINED', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.engagement_agent_user')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Inactive_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avdsname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('liked', models.IntegerField(default=0)),
                ('commented', models.IntegerField(default=0)),
                ('shared', models.IntegerField(default=0)),
                ('followed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.engagement_agent_user')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_otp', models.CharField(default='000000', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
