# Generated by Django 3.2.6 on 2021-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTA_ALL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
