# Generated by Django 3.2.6 on 2021-09-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INSTA_ALL', '0002_alter_orders_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='custom_user_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='image_url',
            field=models.TextField(),
        ),
    ]
