# Generated by Django 3.2.3 on 2022-06-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_user_details_comment_user_details_reaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='engagements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inactive_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.DeleteModel(
            name='comment_view',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='Engagements',
        ),
        migrations.DeleteModel(
            name='inactive_user',
        ),
        migrations.DeleteModel(
            name='view',
        ),
    ]
